/// Flutter icons CustomIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';

  static const IconData bar_chart =
      const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData at_sign = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData bar_chart_ =
      const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData bookmark =
      const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData chevron_down =
      const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData chevron_left =
      const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData chevron_right =
      const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData chevron_up =
      const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData credit_card =
      const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData crosshair =
      const IconData(0xe860, fontFamily: _kFontFam);
  static const IconData download_cloud =
      const IconData(0xe863, fontFamily: _kFontFam);
  static const IconData download =
      const IconData(0xe864, fontFamily: _kFontFam);
  static const IconData edit_ = const IconData(0xe866, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe867, fontFamily: _kFontFam);
  static const IconData edit_1 = const IconData(0xe868, fontFamily: _kFontFam);
  static const IconData external_link =
      const IconData(0xe869, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData file_text =
      const IconData(0xe870, fontFamily: _kFontFam);
  static const IconData file_plus =
      const IconData(0xe873, fontFamily: _kFontFam);
  static const IconData flag = const IconData(0xe876, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe879, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData inbox = const IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData layers = const IconData(0xe87e, fontFamily: _kFontFam);
  static const IconData link_ = const IconData(0xe882, fontFamily: _kFontFam);
  static const IconData link = const IconData(0xe884, fontFamily: _kFontFam);
  static const IconData log_in = const IconData(0xe885, fontFamily: _kFontFam);
  static const IconData list = const IconData(0xe886, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe887, fontFamily: _kFontFam);
  static const IconData log_out = const IconData(0xe888, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe88a, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe88f, fontFamily: _kFontFam);
  static const IconData message_circle =
      const IconData(0xe890, fontFamily: _kFontFam);
  static const IconData message_square =
      const IconData(0xe891, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe898, fontFamily: _kFontFam);
  static const IconData monitor = const IconData(0xe899, fontFamily: _kFontFam);
  static const IconData more_vertical =
      const IconData(0xe89a, fontFamily: _kFontFam);
  static const IconData more_horizontal =
      const IconData(0xe89b, fontFamily: _kFontFam);
  static const IconData package = const IconData(0xe8a1, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe8aa, fontFamily: _kFontFam);
  static const IconData pie_chart =
      const IconData(0xe8ac, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe8ae, fontFamily: _kFontFam);
  static const IconData printer = const IconData(0xe8b3, fontFamily: _kFontFam);
  static const IconData power = const IconData(0xe8b4, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe8bd, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe8c1, fontFamily: _kFontFam);
  static const IconData shield = const IconData(0xe8c2, fontFamily: _kFontFam);
  static const IconData settings =
      const IconData(0xe8c3, fontFamily: _kFontFam);
  static const IconData slash = const IconData(0xe8c9, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe8cd, fontFamily: _kFontFam);
  static const IconData tag = const IconData(0xe8d2, fontFamily: _kFontFam);
  static const IconData unlock = const IconData(0xe8e4, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe8e9, fontFamily: _kFontFam);
  static const IconData zap = const IconData(0xe8f8, fontFamily: _kFontFam);
  static const IconData hash = const IconData(0xe8fd, fontFamily: _kFontFam);
  static const IconData shopping_cart =
      const IconData(0xe905, fontFamily: _kFontFam);
  static const IconData star_on = const IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData heart_on =
      const IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData bar_chart_line_ =
      const IconData(0xe912, fontFamily: _kFontFam);
  static const IconData bar_chart_line =
      const IconData(0xe913, fontFamily: _kFontFam);
  static const IconData code = const IconData(0xe915, fontFamily: _kFontFam);
  static const IconData dollar_sign =
      const IconData(0xe917, fontFamily: _kFontFam);
}
